# Generated by Django 3.2 on 2021-04-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tasktable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('critical_files', 'Critical'), ('references', 'Reference'), ('submissions', 'Submission')], max_length=14)),
                ('file', models.FileField(upload_to=tasktable.models.project_file_space)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('founding_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=260)),
                ('assigned_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Assigned')),
                ('due_date', models.DateTimeField(verbose_name='Date Due')),
                ('importance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6)),
                ('state', models.CharField(blank=True, choices=[('On Track', 'On Track'), ('Stuck', 'Stuck'), ('Ready for Approval', 'Ready for Approval'), ('Behind Schedule', 'Behind Schedule')], max_length=18)),
                ('approved', models.BooleanField(default=False)),
                ('pre_approved', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignees', models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasktable.project')),
                ('references', models.ManyToManyField(blank=True, related_name='references', to='tasktable.File')),
                ('status', models.ManyToManyField(blank=True, to='tasktable.Status')),
                ('submissions', models.ManyToManyField(blank=True, to='tasktable.File')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('date_time_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_ago', models.CharField(blank=True, max_length=20, null=True)),
                ('link_url', models.CharField(blank=True, max_length=15, null=True)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktable.project'),
        ),
    ]
